# Generated by Django 3.1.3 on 2021-01-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_attendence_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_pic',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
