# Generated by Django 3.1.3 on 2021-01-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_student_qr_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
